version: "3.8"

services:
  app:
    # Use the official TensorFlow image as the base
    image: tensorflow/tensorflow:latest-gpu
    
    # Give your container a consistent name
    container_name: my_tf_app
    tty: true
    stdin_open: true
    
    # This is the key step to "copy" your code.
    # It mounts the entire repository folder into the /app directory in the container.
    volumes:
      - .:/app
      
    # This sets the starting directory inside the container to /app.
    working_dir: /app
      
    # This command runs after the container starts and the volume is mounted.
    # It first installs your requirements and then starts your main Python script.
    #command: >
      #sh -c "pip install -r requirements.txt && python containerTest.py"
      
    # You can add ports here if your application is a web server
    # ports:

    #   - "8000:8000"


