version: "3.8"

services:
  app:
    # Use the official TensorFlow image as the base
    image: tensorflow/tensorflow:2.15.0-gpu
    
    # Give your container a consistent name
    container_name: rt-training
    
    # Mounts the current folder (which includes your key) into /app
    volumes:
      - .:/app
      
    # Sets the starting directory inside the container to /app
    working_dir: /app

    # This tells Google tools to use your key file automatically
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/docker-downloader-92646cf12baa.json
      
    # GPU allocation
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']
              capabilities: [gpu]

    # --- THIS COMMAND SECTION DOES ALL YOUR SETUP ---
    command: sh -c "
        apt-get update && 
        apt-get install -y openssh-server unzip gdown &&
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
        mkdir -p /run/sshd &&
        /usr/sbin/sshd &&
        echo 'Container is set up, authenticated, and SSH is running.' &&
        echo 'Ready for you to connect and run commands manually.' &&
        tail -f /dev/null"

    # Keep these to allow you to attach
    tty: true
    stdin_open: true

    # Your port mapping
    ports:
      - "9090:90"