version: "3.8"

services:
  robot:
    build: .                   # build the Dockerfile from repo
    container_name: robot_container_git
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Berlin
