version: "3.8"

services:
  app:
    image: tensorflow/tensorflow:2.15.0-gpu
    container_name: my_tf_app
    volumes:
      - .:/app
      - gcloud_config:/root/.config/gcloud # Persists your login
    ports:
      - "2222:22"
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']
              capabilities: [gpu]
    command: sh -c "
        apt-get update && apt-get install -y openssh-server google-cloud-cli &&
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
        /usr/sbin/sshd &&
        tail -f /dev/null" # Keeps the container running and idle
    tty: true
    stdin_open: true

volumes:
  gcloud_config: