version: "3.9"

services:
  app:
    # Use the official TensorFlow image as the base
    image: tensorflow/tensorflow:2.15.0-gpu
    
    # Give your container a consistent name
    container_name: rt-training
    
    # Mounts the current folder (which includes your key) into /app
    volumes:
      - .:/app
      
    # Sets the starting directory inside the container to /app
    working_dir: /app

    # --- THIS IS THE ONLY PART YOU NEED FOR AUTHENTICATION ---
    environment:
      # This tells Google tools to use your key file automatically
      - GOOGLE_APPLICATION_CREDENTIALS=/app/docker-downloader-92646cf12baa.json
      
    # GPU allocation
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1', '7', '8']
              capabilities: [gpu]

    # This command just keeps the container running so you can connect
    command: tail -f /dev/null

    # Keep these to allow you to attach
    tty: true
    stdin_open: true

    # Your port mapping
    ports:
      - "9090:90"