version: "1.2"

services: 
  robot:
    image: tensorflow/tensorflow:latest-gpu
    container_name: robot_container_git
    tty: true
    stdin_open: true
    ports:
      - "3000:3000/tcp"
    volumes:
      - app:/Training/
    environment:
      TZ: "Europe/Berlin"

volumes: 
  app:
     driver: local






