version: "3.8" # It's good practice to use a more recent version like 3.8

services:
  robot:
    image: tensorflow/tensorflow:latest-gpu
    container_name: robot_container_git
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      # This is the key change: Map the repo root to /Training/
      - .:/Training/
    working_dir: /Training/ # Sets the default directory inside the container
    environment:
      - TZ=Europe/Berlin
    # You need a command to install requirements and run your code
    command: sh -c "pip install -r requirements.txt"

# The separate volumes definition is no longer needed for your code











