version: "3.8"

services:
  robot:
    image: tensorflow/tensorflow:latest-gpu
    container_name: robot_container_git
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    
    # This maps the entire repository root into the /app directory in the container
    volumes:
      - .:/app
      
    # This sets the default directory for all subsequent commands
    working_dir: /app
    
    environment:
      - TZ=Europe/Berlin
      
    # This command now runs inside /app, where requirements.txt is located
    # IMPORTANT: Replace 'your_main_script.py' with the actual name of your Python script
    command: sh -c "pip install -r requirements.txt && python your_main_script.py"
