version: "1.2"

services: 
  robot:
    image: tensorflow/tensorflow:latest-gpu
    container_name: robot_container_git
    tty: true
    stdin_open: true
    command: pip install rlds dm-reverb[tensorflow]
    command: pip install jaxlib==0.4.38
    command: pip install jax==0.4.38
    command: pip uninstall -y jax-cuda12-pjrt jax-cuda12-plugin
    command: pip install "jax[cuda12_pip]==0.4.38" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    command: pip install flax
    command: pip install orbax-checkpointing
    ports:
      - "3000:3000/tcp"
    volumes:
      - app:/Training/
    environment:
      TZ: "Europe/Berlin"

volumes: 
  app:
     driver: local



